services:
  db:
    image: mysql:8.0
    container_name: tft_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tft_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  web:
    build: ./web
    container_name: tft_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tft_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - RIOT_API_KEY=RGAPI-1b17c775-0cbb-4c73-bc9a-15d45ab0bd83
    ports:
      - "8080:8080"
    restart: always

  batch:
    build: ./batch
    container_name: tft_batch
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tft_db?useSSL=false&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - RIOT_API_KEY=RGAPI-1b17c775-0cbb-4c73-bc9a-15d45ab0bd83
    restart: always

volumes:
  db_data:
